### ISSUE TITLE
chat.initialize: parameters invalid

### ISSUE THREAD

**Issue by SKDDEFEATLESS** [thecmart/manuals#9]
Parameters given in the sample code:
ChatSDK.initialize(config.build(), new FirebaseNetworkAdapter(), new BaseInterfaceAdapter(context));
Expected:
ChatSDK.initialize(context,config,networkAdapterClass,interfaceAdapterClass)

Can you please help me with the right parameter values

**Comment by bensmiley** [comment]
https://github.com/chat-sdk/chat-sdk-android#initializing-the-chat-sdk
